services:
  trenchess:
    build:
      context: .
      target: prod
    ports:
      - "80:80"
    environment:
      - VITE_SERVER_URL=http://your-production-url:3001
    networks:
      - trenchess-net

  server:
    build:
      context: ./server
      target: prod
    ports:
      - "3001:3001"
    networks:
      - trenchess-net

networks:
  trenchess-net:
    driver: bridge
